-- 主题库 (2026-09-16): 一次装一批主流配色, 给 dashboard 的 "Theme" 项 (键 t) 挑。
-- 来源: dotfyle 配色榜前 25 + GitHub topic:neovim-colorscheme 按 star 的前排, 剔掉工具类
--       (styler / lsp-colors / bg.nvim / highlite 之类) 和框架, 另加了几个经典 vim 配色。
-- 排除掉的: romainl/Apprentice (在这版 nvim 上直接报 E423 ctermul, 上游没修)、gbprod/nord.nvim
--       (与 shaunsingh/nord.nvim 目录名撞车)。
-- 全部 lazy = true: 只在 picker 里预览或真正选中时才加载, 不拖启动速度。
--   (本项目 lazy.setup 的 defaults.lazy = false, 漏写 lazy = true 会让它们开机全加载!)
-- 不写 opts / config: 纯 colorscheme 插件没有 setup(), 给 opts 会让 LazyVim 去调
--   require().setup() → nil 报错 (oxocarbon 当年就是这个坑)。
-- 注意 lush.nvim 不是主题, 是 bluloco / zenbones 系主题的依赖包, 删它那 18 个主题会报错。
-- 不想要的直接删那一行, 剩下的互不影响; 想加新的照一行 "owner/repo" 加即可。
return {
  { "rebelot/kanagawa.nvim", lazy = true },
  { "rktjmp/lush.nvim", lazy = true }, -- 若干主题 (bluloco / zenbones 全家) 的运行时依赖
  { "rose-pine/neovim", name = "rose-pine", lazy = true },
  { "EdenEast/nightfox.nvim", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },
  { "sainnhe/gruvbox-material", lazy = true },
  { "projekt0n/github-nvim-theme", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "scottmckendry/cyberdream.nvim", lazy = true },
  { "Mofiqul/vscode.nvim", lazy = true },
  { "olimorris/onedarkpro.nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "marko-cerovac/material.nvim", lazy = true },
  { "shaunsingh/nord.nvim", lazy = true },
  { "craftzdog/solarized-osaka.nvim", lazy = true },
  { "sainnhe/sonokai", lazy = true },
  { "AlexvZyl/nordic.nvim", lazy = true },
  { "bluz71/vim-moonfly-colors", lazy = true },
  { "neanias/everforest-nvim", lazy = true },
  { "tiagovla/tokyodark.nvim", lazy = true },
  { "ribru17/bamboo.nvim", lazy = true },
  { "savq/melange-nvim", lazy = true },
  { "sainnhe/edge", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "morhetz/gruvbox", lazy = true },
  { "kepano/flexoki", lazy = true },
  { "vague-theme/vague.nvim", lazy = true },
  { "zenbones-theme/zenbones.nvim", lazy = true },
  { "bluz71/vim-nightfly-colors", lazy = true },
  { "jacoborus/tender.vim", lazy = true },
  { "evergardentheme/nvim", name = "evergarden", lazy = true },
  { "rmehri01/onenord.nvim", lazy = true },
  { "Shatur/neovim-ayu", lazy = true },
  { "slugbyte/lackluster.nvim", lazy = true },
  { "xero/miasma.nvim", lazy = true },
  { "olivercederborg/poimandres.nvim", lazy = true },
  { "uloco/bluloco.nvim", lazy = true },
  { "luisiacc/gruvbox-baby", lazy = true },
  { "ramojus/mellifluous.nvim", lazy = true },
  { "miikanissi/modus-themes.nvim", lazy = true },
  { "aktersnurra/no-clown-fiesta.nvim", lazy = true },
  { "thesimonho/kanagawa-paper.nvim", lazy = true },
  { "patstockwell/vim-monokai-tasty", lazy = true },
  { "ray-x/aurora", lazy = true },
  { "metalelf0/black-metal-theme-neovim", lazy = true },
  { "oskarnurm/koda.nvim", lazy = true },
  { "oxfist/night-owl.nvim", lazy = true },
  { "maxmx03/fluoromachine.nvim", lazy = true },
  { "maxmx03/solarized.nvim", lazy = true },
  { "Everblush/nvim", name = "everblush", lazy = true },
  { "rockerBOO/boo-colorscheme-nvim", lazy = true },
  { "zootedb0t/citruszest.nvim", lazy = true },
  { "datsfilipe/vesper.nvim", lazy = true },
  { "NTBBloodbath/doom-one.nvim", lazy = true },
  { "dasupradyumna/midnight.nvim", lazy = true },
  { "blazkowolf/gruber-darker.nvim", lazy = true },
  { "darkvoid-theme/darkvoid.nvim", lazy = true },
  { "casedami/neomodern.nvim", lazy = true },
  { "yorumicolors/yorumi.nvim", lazy = true },
  { "ilof2/posterpole.nvim", lazy = true },
  { "Verf/deepwhite.nvim", lazy = true },
  { "ThorstenRhau/token", lazy = true },
  { "dgox16/oldworld.nvim", lazy = true },
  { "loctvl842/monokai-pro.nvim", lazy = true },
  { "tanvirtin/monokai.nvim", lazy = true },
  { "joshdick/onedark.vim", lazy = true },
  { "arcticicestudio/nord-vim", lazy = true },
  { "altercation/vim-colors-solarized", lazy = true },
  { "nanotech/jellybeans.vim", lazy = true },
  { "sickill/vim-monokai", lazy = true },
  { "tomasr/molokai", lazy = true },
}
